name: LintR-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lintr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: ðŸ“‹ Restore renv (force native rebuild)
        if: matrix.config.os != 'windows-latest'
        run: |
          Rscript -e "renv::restore(prompt = FALSE, rebuild = TRUE)"

      - name: Install curl from P3M
        if: matrix.config.os != 'windows-latest'
        run: |
          R -e 'install.packages(c("lintr", "devtools", "curl"),
          repos = c(
          p3m = "https://p3m.dev/cran/__linux__/manylinux_2_28/latest"
          ))'

      - name: Install package
        run: Rscript -e 'devtools::install()'

      - name: Run lintr
        shell: Rscript {0}
        run: |
          lints <- lintr::lint_package()
          for (lint in lints) print(lint)
          quit(status = length(lints) > 0)
