name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    runs-on: ${{ matrix.config.os }}

    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest,   r: 'release'}
        - {os: windows-latest, r: 'release'}
        - {os: ubuntu-latest, r: 'release'}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pandoc for windows-latest
        if: matrix.config.os == 'windows-latest'
        run: |
          Set-ExecutionPolicy AllSigned
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install pandoc

      - name: Setup Pandoc for ubuntu-latest
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install -y r-cran-xml
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev

      - name: Setup Pandoc for macOS-latest
        if: matrix.config.os == 'macOS-latest'
        run: |
          brew install pandoc

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          needs: check
          pak-version: 'stable'
          extra-packages: any::devtools, any::optparse, local::.

      - name: Install system deps for curl
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev

      - name: Install curl from source with static OpenSSL
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          R -e 'install.packages("curl", type="source", configure.args="--with-static-libssl")'

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"warning"'
          check-dir: '"check"'
